// For text and quoted attributes generated by the library, not user HTML layouts.
const escapeHTML = (value: string | number | null) =>
  String(value).replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character] as string);

export default escapeHTML;
