const styles = {
  calendar: 'vc',
  controls: 'vc-controls',
  grid: 'vc-grid',
  column: 'vc-column',
  header: 'vc-header',
  headerContent: 'vc-header__content',
  month: 'vc-month',
  year: 'vc-year',
  arrowPrev: 'vc-arrow vc-arrow_prev',
  arrowNext: 'vc-arrow vc-arrow_next',
  wrapper: 'vc-wrapper',
  content: 'vc-content',
  months: 'vc-months',
  monthsRow: 'vc-months__row',
  monthsCell: 'vc-months__cell',
  monthsMonth: 'vc-months__month',
  years: 'vc-years',
  yearsRow: 'vc-years__row',
  yearsCell: 'vc-years__cell',
  yearsYear: 'vc-years__year',
  week: 'vc-week',
  weekDay: 'vc-week__day',
  weekDayBtn: 'vc-week__day-btn',
  weekNumbers: 'vc-week-numbers',
  weekNumbersTitle: 'vc-week-numbers__title',
  weekNumbersContent: 'vc-week-numbers__content',
  weekNumber: 'vc-week-number',
  collapse: 'vc-collapse',
  dates: 'vc-dates',
  datesRow: 'vc-dates__row',
  date: 'vc-date',
  dateBtn: 'vc-date__btn',
  datePopup: 'vc-date__popup',
  dateRangeTooltip: 'vc-date-range-tooltip',
  time: 'vc-time',
  timeContent: 'vc-time__content',
  timeHour: 'vc-time__hour',
  timeMinute: 'vc-time__minute',
  timeKeeping: 'vc-time__keeping',
  timeRanges: 'vc-time__ranges',
  timeRange: 'vc-time__range',
};

export default styles;
