const classes = {
  calendar: 'vanilla-calendar',
  controls: 'vanilla-calendar-controls',
  grid: 'vanilla-calendar-grid',
  column: 'vanilla-calendar-column',
  header: 'vanilla-calendar-header',
  headerContent: 'vanilla-calendar-header__content',
  month: 'vanilla-calendar-month',
  year: 'vanilla-calendar-year',
  arrowPrev: 'vanilla-calendar-arrow vanilla-calendar-arrow_prev',
  arrowNext: 'vanilla-calendar-arrow vanilla-calendar-arrow_next',
  wrapper: 'vanilla-calendar-wrapper',
  content: 'vanilla-calendar-content',
  months: 'vanilla-calendar-months',
  monthsMonth: 'vanilla-calendar-months__month',
  years: 'vanilla-calendar-years',
  yearsYear: 'vanilla-calendar-years__year',
  week: 'vanilla-calendar-week',
  weekDay: 'vanilla-calendar-week__day',
  weekNumbers: 'vanilla-calendar-week-numbers',
  weekNumbersTitle: 'vanilla-calendar-week-numbers__title',
  weekNumbersContent: 'vanilla-calendar-week-numbers__content',
  weekNumber: 'vanilla-calendar-week-number',
  dates: 'vanilla-calendar-dates',
  date: 'vanilla-calendar-date',
  dateBtn: 'vanilla-calendar-date__btn',
  datePopup: 'vanilla-calendar-date__popup',
  time: 'vanilla-calendar-time',
  timeContent: 'vanilla-calendar-time__content',
  timeHour: 'vanilla-calendar-time__hour',
  timeMinute: 'vanilla-calendar-time__minute',
  timeKeeping: 'vanilla-calendar-time__keeping',
  timeRanges: 'vanilla-calendar-time__ranges',
  timeRange: 'vanilla-calendar-time__range',
};

export default classes;
