const classes = {
  calendar: 'vanilla-calendar',
  controls: 'vanilla-calendar-controls',
  grid: 'vanilla-calendar-grid',
  column: 'vanilla-calendar-column',
  header: 'vanilla-calendar-header',
  headerContent: 'vanilla-calendar-header__content',
  month: 'vanilla-calendar-month',
  year: 'vanilla-calendar-year',
  arrowPrev: 'vanilla-calendar-arrow vanilla-calendar-arrow_prev',
  arrowNext: 'vanilla-calendar-arrow vanilla-calendar-arrow_next',
  wrapper: 'vanilla-calendar-wrapper',
  content: 'vanilla-calendar-content',
  week: 'vanilla-calendar-week',
  weekDay: 'vanilla-calendar-week__day',
  days: 'vanilla-calendar-days',
  months: 'vanilla-calendar-months',
  monthsMonth: 'vanilla-calendar-months__month',
  years: 'vanilla-calendar-years',
  yearsYear: 'vanilla-calendar-years__year',
  weekNumbers: 'vanilla-calendar-week-numbers',
  weekNumbersTitle: 'vanilla-calendar-week-numbers__title',
  weekNumbersContent: 'vanilla-calendar-week-numbers__content',
  weekNumber: 'vanilla-calendar-week-number',

  day: 'vanilla-calendar-day',
  dayHoverFirst: 'vanilla-calendar-day_hover-first',
  dayHoverLast: 'vanilla-calendar-day_hover-last',
  dayHoverIntermediate: 'vanilla-calendar-day_hover-intermediate',
  daySelectedFirst: 'vanilla-calendar-day_selected-first',
  daySelectedLast: 'vanilla-calendar-day_selected-last',
  daySelectedIntermediate: 'vanilla-calendar-day_selected-intermediate',

  dayPopup: 'vanilla-calendar-day__popup',

  dayBtn: 'vanilla-calendar-day__btn',
  dayBtnPrev: 'vanilla-calendar-day__btn_prev',
  dayBtnNext: 'vanilla-calendar-day__btn_next',
  dayBtnToday: 'vanilla-calendar-day__btn_today',
  dayBtnSelected: 'vanilla-calendar-day__btn_selected',
  dayBtnHover: 'vanilla-calendar-day__btn_hover',
  dayBtnDisabled: 'vanilla-calendar-day__btn_disabled',
  dayBtnWeekend: 'vanilla-calendar-day__btn_weekend',
  dayBtnHoliday: 'vanilla-calendar-day__btn_holiday',

  time: 'vanilla-calendar-time',
  timeContent: 'vanilla-calendar-time__content',
  timeHours: 'vanilla-calendar-time__hours',
  timeMinutes: 'vanilla-calendar-time__minutes',
  timeKeeping: 'vanilla-calendar-time__keeping',
  timeRanges: 'vanilla-calendar-time__ranges',
  timeRange: 'vanilla-calendar-time__range',

  isFocus: 'vanilla-calendar-is-focus',
};

export default classes;
