name: Testing pull request

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v7.0.0
        with:
          node-version-file: package.json
      - uses: pnpm/action-setup@v6.1.0
        with:
          cache: true
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check source and build package
        run: pnpm lint && pnpm package:build && pnpm build
      - name: Testing
        run: pnpm cypress:run && node --test tests/package/package.test.mjs
