name: Testing pull request

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Setup npm package
        run: npm install
      - name: Testing
        uses: cypress-io/github-action@v7.4.3
        with:
          start: npm run dev
